# Generated by Django 6.0.4 on 2026-04-28 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('draw_mode', models.CharField(choices=[('random', 'Random (standard lottery)'), ('algorithmic', 'Algorithmic (score-weighted)')], default='random', max_length=15)),
                ('drawn_numbers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending — accepting entries'), ('simulated', 'Simulated — preview only'), ('published', 'Published — official results')], default='pending', max_length=12)),
                ('jackpot_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('jackpot_rolled_over', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draws', to=settings.AUTH_USER_MODEL)),
                ('rollover_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollover_to', to='draws.monthlydraw')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserDrawEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numbers', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draws.monthlydraw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'draw')},
            },
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_numbers', models.JSONField(default=list)),
                ('match_count', models.PositiveSmallIntegerField(default=0)),
                ('prize_tier', models.CharField(choices=[('none', 'No Prize'), ('3_match', '3-Number Match'), ('4_match', '4-Number Match'), ('5_match', '5-Number Match — Jackpot')], default='none', max_length=10)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_results', to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='draws.monthlydraw')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='draws.userdrawentry')),
            ],
            options={
                'unique_together': {('draw', 'user')},
            },
        ),
    ]
