# Generated by Django 6.0.4 on 2026-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlydraw',
            name='jackpot_amount',
        ),
        migrations.AddField(
            model_name='monthlydraw',
            name='pool_3match',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlydraw',
            name='pool_4match',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlydraw',
            name='pool_5match',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlydraw',
            name='pool_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='monthlydraw',
            name='rollover_jackpot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='drawresult',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
