# Generated by Django 6.0.4 on 2026-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_remove_monthlydraw_jackpot_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresult',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='payment_status',
            field=models.CharField(choices=[('none', 'No Payment'), ('pending', 'Pending Payment'), ('paid', 'Paid')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='draw_proofs/'),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Required'), ('pending', 'Pending Upload'), ('submitted', 'Proof Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=15),
        ),
    ]
